# Creamos un contenedor de mysql con la imagen de mysql 5.7
From mysql:5.7
# Definimos las variables de entorno de nuestra bbdd
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=accwe-hospital
# Definimos el volumen de la bbdd
VOLUME /var/lib/mysql
# Exponemos el puerto 3306
EXPOSE 3306
